### ISSUE TITLE
An import bug at win32 platform

### ISSUE THREAD

**Issue by yumendy** [airtoxin/Achievement#2]
Hello, I found it there is an import bug when this used in win32 platform. It can't append the path of the dir, so it can't import models in other files.
At line 8 of `override_shortcutkey.py` and line 8 of `achievement.py`.
I suggest the code can be change as below:

if sys.platform == 'win32':
    sys.path.append("\\".join(__file__.split("\\")[:-1]))
else:
    sys.path.append("/".join(__file__.split("/")[:-1]))

**Comment by airtoxin** [comment]
@yumendy 
I'll fix it. thanks

**Comment by airtoxin** [comment]
hi, @yumendy 
check 3730883aaa9dd99cfff71e949ec7af09ebd323fb

**Comment by yumendy** [comment]
It's ok now. Thx~~ : )
